[project]
name = "openai-anpr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.69.0",
    "opencv-python>=4.11.0.86",
    "ultralytics>=8.3.98",
]
